version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/"
    groups:
      trino:
        patterns:
          - "io.trino*"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "io.trino:trino-testing"
      - dependency-name: "io.trino:trino-root"
      - dependency-name: "io.tiledb:tiledb-java"
    reviewers:
      - "DimitrisStaratzis"
