name: TileDB-Trino

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
    branches:
      - 'master'
  pull_request:

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-13 ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          check-latest: true

      - run: |
          mvn checkstyle:checkstyle
        shell: bash
        name: checkStyle

      - run: |
          mvn clean package -e -DskipTests
        shell: bash
        name: checkFormat

      - run: |
          mvn test
        shell: bash
        name: test

  Release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [Test]
    name: Create-Release
    runs-on: ubuntu-latest
    steps:
      - name: Set-up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          check-latest: true

      - name: Checkout
        uses: actions/checkout@v4

      - name: Create-Jars
        run: set +e; mvn clean package -DskipTests; mkdir jars/; cp ./target/*.jar jars/

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: jars/*.jar
          tag_name: ${{ github.event.release.tag_name }}
          name: ${{ github.event.release.tag_name }}
          draft: false
          prerelease: false
